import { int, mysqlEnum, mysqlTable, text, timestamp, varchar, boolean, json } from "drizzle-orm/mysql-core";

/**
 * Core user table backing auth flow.
 * Extend this file with additional tables as your product grows.
 * Columns use camelCase to match both database fields and generated types.
 */
export const users = mysqlTable("users", {
  /**
   * Surrogate primary key. Auto-incremented numeric value managed by the database.
   * Use this for relations between tables.
   */
  id: int("id").autoincrement().primaryKey(),
  /** Manus OAuth identifier (openId) returned from the OAuth callback. Unique per user. */
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

/**
 * Leads table for capturing potential customer information
 * Stores all lead submissions from the website contact forms
 */
export const leads = mysqlTable("leads", {
  id: int("id").autoincrement().primaryKey(),
  firstName: varchar("firstName", { length: 100 }).notNull(),
  lastName: varchar("lastName", { length: 100 }).notNull(),
  email: varchar("email", { length: 320 }).notNull(),
  phone: varchar("phone", { length: 50 }),
  neighborhood: varchar("neighborhood", { length: 100 }),
  budget: varchar("budget", { length: 100 }),
  timeline: varchar("timeline", { length: 100 }),
  message: text("message"),
  source: varchar("source", { length: 100 }).default("website"),
  status: mysqlEnum("status", ["new", "contacted", "qualified", "converted", "closed"]).default("new").notNull(),
  notificationSent: boolean("notificationSent").default(false).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type Lead = typeof leads.$inferSelect;
export type InsertLead = typeof leads.$inferInsert;

/**
 * Newsletter subscribers table
 */
export const subscribers = mysqlTable("subscribers", {
  id: int("id").autoincrement().primaryKey(),
  email: varchar("email", { length: 320 }).notNull().unique(),
  active: boolean("active").default(true).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type Subscriber = typeof subscribers.$inferSelect;
export type InsertSubscriber = typeof subscribers.$inferInsert;

/**
 * Automated articles/posts table
 * Stores SEO-optimized content generated by the marketing bot
 */
export const articles = mysqlTable("articles", {
  id: int("id").autoincrement().primaryKey(),
  slug: varchar("slug", { length: 255 }).notNull().unique(),
  title: varchar("title", { length: 500 }).notNull(),
  excerpt: text("excerpt"),
  content: text("content").notNull(),
  category: varchar("category", { length: 100 }).notNull(),
  tags: text("tags"), // JSON array stored as text
  metaDescription: varchar("metaDescription", { length: 500 }),
  metaKeywords: varchar("metaKeywords", { length: 500 }),
  featuredImage: varchar("featuredImage", { length: 500 }),
  authorName: varchar("authorName", { length: 100 }).default("Kevin Rea"),
  authorEmail: varchar("authorEmail", { length: 320 }).default("kevin@reacohomes.com"),
  authorPhone: varchar("authorPhone", { length: 50 }).default("541-390-9848"),
  status: mysqlEnum("status", ["draft", "published", "archived"]).default("published").notNull(),
  views: int("views").default(0).notNull(),
  clicks: int("clicks").default(0).notNull(),
  publishedAt: timestamp("publishedAt"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type Article = typeof articles.$inferSelect;
export type InsertArticle = typeof articles.$inferInsert;

/**
 * Marketing metrics table
 * Tracks reach, engagement, and distribution of content
 */
export const marketingMetrics = mysqlTable("marketing_metrics", {
  id: int("id").autoincrement().primaryKey(),
  articleId: int("articleId"),
  platform: varchar("platform", { length: 100 }).notNull(), // e.g., "google", "social", "press_release"
  impressions: int("impressions").default(0).notNull(),
  clicks: int("clicks").default(0).notNull(),
  conversions: int("conversions").default(0).notNull(),
  reach: int("reach").default(0).notNull(),
  distributedTo: text("distributedTo"), // JSON array of distribution targets
  distributedAt: timestamp("distributedAt"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type MarketingMetric = typeof marketingMetrics.$inferSelect;
export type InsertMarketingMetric = typeof marketingMetrics.$inferInsert;

/**
 * Bot activity log table
 * Tracks all actions taken by the marketing optimization bot
 */
export const botActivityLog = mysqlTable("bot_activity_log", {
  id: int("id").autoincrement().primaryKey(),
  activityType: mysqlEnum("activityType", [
    "content_generation",
    "seo_optimization", 
    "keyword_research",
    "trend_analysis",
    "distribution",
    "lead_outreach",
    "performance_analysis",
    "learning_update"
  ]).notNull(),
  description: text("description").notNull(),
  status: mysqlEnum("status", ["started", "in_progress", "completed", "failed"]).default("started").notNull(),
  result: text("result"), // JSON result data
  articlesGenerated: int("articlesGenerated").default(0),
  leadsGenerated: int("leadsGenerated").default(0),
  trafficIncrease: int("trafficIncrease").default(0),
  duration: int("duration"), // in seconds
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  completedAt: timestamp("completedAt"),
});

export type BotActivityLog = typeof botActivityLog.$inferSelect;
export type InsertBotActivityLog = typeof botActivityLog.$inferInsert;

/**
 * Bot learning/optimization state
 * Stores the bot's learned patterns and optimization strategies
 */
export const botLearningState = mysqlTable("bot_learning_state", {
  id: int("id").autoincrement().primaryKey(),
  category: varchar("category", { length: 100 }).notNull(), // e.g., "keywords", "topics", "timing"
  key: varchar("key", { length: 255 }).notNull(),
  value: text("value").notNull(), // JSON data
  score: int("score").default(0), // effectiveness score
  lastUpdated: timestamp("lastUpdated").defaultNow().onUpdateNow().notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type BotLearningState = typeof botLearningState.$inferSelect;
export type InsertBotLearningState = typeof botLearningState.$inferInsert;

/**
 * Distribution queue table
 * Queue for content to be distributed to various platforms
 */
export const distributionQueue = mysqlTable("distribution_queue", {
  id: int("id").autoincrement().primaryKey(),
  articleId: int("articleId").notNull(),
  platform: varchar("platform", { length: 100 }).notNull(),
  status: mysqlEnum("status", ["pending", "processing", "completed", "failed"]).default("pending").notNull(),
  scheduledFor: timestamp("scheduledFor"),
  processedAt: timestamp("processedAt"),
  result: text("result"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type DistributionQueue = typeof distributionQueue.$inferSelect;
export type InsertDistributionQueue = typeof distributionQueue.$inferInsert;
